name: Production

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install npm packages
        working-directory: ./illiana-app
        run: npm i
        
      - name: Install Angular CLI
        run: sudo npm i -g @angular/cli@13.2.4 > /dev/null && ng version
  
      - name: Build
        working-directory: ./illiana-app
        run: ng build --configuration production
      
      - name: Deploy
        uses: shallwefootball/s3-upload-action@v1.3.0
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'illiana-app/dist/illiana-app'
          destination_dir: ''
