name: Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install npm packages
        working-directory: ./illiana-app
        run: npm i

      - name: Install Angular CLI
        run: sudo npm i -g @angular/cli@20.3.3 > /dev/null && ng version

      - name: Build
        working-directory: ./illiana-app
        run: ng build --configuration production
